### ISSUE TITLE
Any reason you haven't wired this up to Mixpanel?

### ISSUE THREAD

**Issue by ChrisSki** [Alephbet/alephbet#11]
I've read all of the tutorials and I think you've done an awesome job with this project and Gimel. After doing our own analysis, we were thinking of wiring this up to Mixpanel since we already use it and are comfortable with it. Have you experimented with this at all and did you find any reasons not to use it? I'd just like to avoid any pitfalls in the event you chose not to include it as a tracking adapter option.

**Comment by gingerlime** [comment]
Thanks, @ChrisSki !

In theory, it should be straightforward to create a mixpanel tracking adapter. The main reason I haven't explored this yet was the mixpanel pricing structure to be honest. Mixpanel charges per event, which can get easily quite expensive if you consider that Alephbet sends an event for every user that participates, and then further events for each goal. It adds up to quite a lot of volume.

keen.io was much more affordable in that sense, so I started with it instead. Even with keen.io, price was becoming a consideration for us, and that's why I've built Gimel.

Practically, the mixpanel API (for extracting data) is generally really good, but I haven't explored exactly how this will be done. I can't foresee any major pitfalls, but can't make any promises either ;-)

Hope this helps?

**Comment by ChrisSki** [comment]
Definitely helps. I'll circle back if I have anything worth contributing!

**Comment by gingerlime** [comment]
Let me know if you need help. I'm also looking for contributors for Gimel in case you're interested :)

**Comment by gingerlime** [comment]
I'm closing this for now, but feel free to re-open if you have anything else to ask or to contribute.

**Comment by ChrisSki** [comment]
All good. I was able to easily create a Segment adapter similar to the others:

```
var tracking_adapter = {
    experiment_start: function(experiment_name, variant) {
      analytics.track(experiment_name, {
        variant: variant,
        event: "participate"
      }, {
        integrations: {
          "All": false,
          "Mixpanel": true
        }
      });
    },
    goal_complete: function(experiment_name, varient, event_name) {
      analytics.track(experiment_name, {
        variant: varient,
        event: event_name
      });
    }
  }

  var button_click_goal = new AlephBet.Goal('button click');
  $("#header-video").on("click", function() {
    button_click_goal.complete();
  });

  var button_color_experiment = new AlephBet.Experiment({
    name: "button color",
    variants: {
      pink: {
        activate: function() {
          console.log("PINK");
        }
      },
      blue: {
        activate: function() {
          console.log("BLUE");
          $("#header-video").attr("style", "background-color: #2962ff");
        }
      }
    },
    tracking_adapter: tracking_adapter
  });

  button_color_experiment.add_goal(button_click_goal);
```

**Comment by gingerlime** [comment]
👍
